### ISSUE TITLE
Pull request merged into wrong branch

### ISSUE THREAD

**Issue by sonicbhoc** [rasheedaboud/Feliz.React.Msal#5]
In my pull request #4 I said that the change would have to be merged into a new branch to continue supporting both the Fable 3 ecosystem and the Fable 4 ecosystem, which are incompatible.

Fable 3 ecosystem would use the code in #4, which master currently points to. These packages have a version number of 0.1.x.

Fable 4 ecosystem would use the code in #2, which is package version 0.2.x.

To fix this, create a new branch at HEAD (call it legacy, maybe?) and reset master to `a4d2ee79967aed169857ddf3461785f70137b75d`.

**Comment by rasheedaboud** [comment]
Oh my.. I followed your suggestion and will push to nuget as well.
