### ISSUE TITLE
Cannot find constructor errors

### ISSUE THREAD

**Issue by mrakgr** [rasheedaboud/Feliz.React.Msal#6]
```
client: .\App.fs(1,1): error FABLE: Cannot find Feliz.React.Msal.Config.Auth constructor
client: .\App.fs(1,1): error FABLE: Cannot find Feliz.React.Msal.Config.Cache constructor
client: .\App.fs(1,1): error FABLE: Cannot find Feliz.React.Msal.Config.MsalConfig constructor
```

This is what I get when I `dotnet` a SAFE Stack application with the `React.Msal` library. I just took the SAFE Stack template and changed it up a bit.

```fs
module App

open Elmish
open Elmish.React
open Feliz
open Feliz.React.Msal
open Shared

#if DEBUG
open Elmish.Debug
open Elmish.HMR
#endif

let client : IPublicClientApplication =
    let auth : Auth = { clientId = Shared.AzureAD.config.ClientId
                        authority = $"https://login.microsoftonline.com/{AzureAD.config.TenantId}"
                        knownAuthorities = [|"login.live.com"|]
                        redirectUri = null
                        postLogoutRedirectUri = null }
    let cache : Cache = { cacheLocation = "sessionStorage"
                          storeAuthStateInCookie = false }
    let config : MsalConfig = { auth = auth
                                cache = cache }
    createClient config

[<ReactComponent>]
let App () =
    Html.text "Hello World!"

open Browser.Dom
ReactDOM.createRoot(document.getElementById("elmish-app")).render(App())
```

**Comment by mrakgr** [comment]
Anyway, I've copied the `Msal.fs` file into my own project and it works.

**Comment by rasheedaboud** [comment]
I'm sorry you had issues. Ill try and reproduce and see what going on.

**Comment by rasheedaboud** [comment]
@mrakgr  please try pkg version 0.2.4. Let me know if issue persists.

FYI @azure/react-msal works with Azure AD or ADB2C. Simply update the config object per docs.

I have build min repo using this lib, it can be found [here](https://github.com/rasheedaboud/Feliz.Auth.Examples).

I will add some basic instructions to this repo to get up and running.

**Comment by mrakgr** [comment]
As you can see, I am still getting a similar error. Here is [the repo](https://github.com/mrakgr/MIP-And-Giraffe/tree/msal-react-bug) where I tested it out.

![Screenshot (182)](https://user-images.githubusercontent.com/6266635/233934445-69c92ef7-a1ee-4ebf-8a6a-2a7542218923.png)

Also, I made a [video](https://youtu.be/_Asoh5Uj0hE) showing how to make a SPA, and I tried the `Msal.React` around the 5-12m range. In the end, I ended up switching to the regular library as I had trouble dealing with the hooks, but since my intent was to use the Elmish pattern, the `msal-browser` library is a better fit for that anyway.

**Comment by rasheedaboud** [comment]
Thanks for the extra info! Just pushed a fix that I've verified on both default SAFE template and default Feliz Template. I did not test running on dotnet 7. Thanks again for the input. 

If it works for you, please let me know and ill update my examples etc.

**Comment by mrakgr** [comment]
Yeah, it works now. The project I've tested it on is .NET 7. Good job!
